let fs = require("fs");

function minify() {
  const append = "const keywords=";
  const uniqueKeywordsSet = new Set(keywords);
  const uniqueKeywords = [...uniqueKeywordsSet].sort();
  fs.writeFile(
    "../../public/keywords.js",
    append + JSON.stringify(uniqueKeywords),
    function (err) {
      if (err) throw err;
      console.log(`${keywords.length} => ${uniqueKeywords.length}`);
      console.log("Saved!");
    }
  );
}

const keywords = [
  "보충제",
  "해조류",
  "알로에베라",
  "아미노산",
  "항산화",
  "아슈와간다",
  "아스타잔틴",
  "프로폴리스",
  "바이오틴",
  "뼈 건강 및 관절",
  "칼슘",
  "코코넛 오일",
  "콜라겐",
  "커큐민",
  "엔자임",
  "섬유소",
  "피쉬 오일",
  "아마씨",
  "마늘",
  "생강 뿌리",
  "은행잎 추출물",
  "인삼",
  "글루코사민",
  "야채 & 슈퍼푸드",
  "헴프",
  "허브",
  "동종요법",
  "히알루론산",
  "크릴 오일",
  "루테인",
  "마카",
  "마그네슘",
  "마누카 꿀",
  "대용식",
  "밀크 씨슬 (실리마린)",
  "미네랄",
  "종합 비타민",
  "버섯",
  "오메가 3 6 9",
  "식물성 단백질",
  "프로바이오틱스",
  "홍국",
  "레스베라트롤",
  "쏘팔메토",
  "스피루리나",
  "세인트 존스워트",
  "비타민B",
  "비타민C",
  "비타민D",
  "비타민E",
  "아연",
  "스포츠",
  "크레아틴",
  "L-아르기닌",
  "L-카르니틴",
  "L-글루타민",
  "MCT 오일",
  "스포츠 바",
  "스포츠 종합비타민",
  "유청 단백질",
  "목욕",
  "아로마 테라피",
  "목욕 & 샤워",
  "바디 & 마사지 오일",
  "헤어 케어",
  "립 케어",
  "로션",
  "상비약",
  "남성 그루밍",
  "구강 케어",
  "퍼스널 케어",
  "뷰티",
  "클렌징 & 스크럽",
  "페이스 마스크 & 필링",
  "기프트 세트",
  "모이스처라이저 & 크림",
  "립 케어",
  "메이크업",
  "메이크업 브러쉬 & 도구",
  "트리트먼트 & 세럼",
  "식료품",
  "베이킹 & 밀가루",
  "버터 & 스프레드",
  "코코넛 오일",
  "커피",
  "꿀 & 감미료",
  "견과류 & 씨앗류",
  "향신료",
  "차",
  "가정용 청소 용품",
  "베이비",
  "목욕, 피부 & 헤어",
  "어린이 건강",
  "이유식",
  "엄마 & 임산부",
  "반려동물",
  "반려동물 사료",
  "반려동물 그루밍",
  "반려동물 용품",
  "노화 방지 & 장수",
  "아유르베다",
  "방광",
  "뼈, 관절 & 연골",
  "두뇌 & 인지력",
  "순환기계",
  "대장",
  "감기 & 독감",
  "디톡스 & 클렌징",
  "소화기계",
  "귀",
  "에너지",
  "눈 & 시력",
  "모발, 피부 & 손발톱",
  "심혈관계",
  "면역력 강화",
  "통증 완화",
  "호흡기계",
  "계절성 알레르기",
  "수면",
  "체중 감량",
  "어린이 건강",
  "남성 건강",
  "여성 건강",
  "노인 건강",
  "Supplements",
  "5-HTP",
  "Algae",
  "Aloe Vera",
  "Amino Acids",
  "Antioxidants",
  "Ashwagandha",
  "Astaxanthin",
  "Bee Propolis",
  "Biotin",
  "Bone & Joint",
  "Calcium",
  "Coconut Oil",
  "Collagen",
  "CoQ10",
  "Curcumin",
  "Enzymes",
  "Fiber",
  "Fish Oil",
  "Flax Seed",
  "Garlic",
  "Ginger Root",
  "Ginkgo Biloba",
  "Ginseng",
  "Glucosamine",
  "Greens & Superfoods",
  "Hemp",
  "Herbs",
  "Homeopathy",
  "Hyaluronic Acid",
  "Krill Oil",
  "Lutein",
  "Maca",
  "Magnesium",
  "Manuka Honey",
  "Meal Replacements",
  "Milk Thistle (Silymarin)",
  "Minerals",
  "Multivitamins",
  "Mushrooms",
  "Omega 3 6 9",
  "Plant Based Protein",
  "Probiotics",
  "Red Yeast Rice",
  "Resveratrol",
  "SAM-e",
  "Saw Palmetto",
  "Spirulina",
  "St. John's Wort",
  "Vitamin B",
  "Vitamin C",
  "Vitamin D",
  "Vitamin E",
  "Zinc",
  "Sports",
  "BCAA",
  "CLA",
  "Creatine",
  "L-Arginine",
  "L-Carnitine",
  "L-Glutamine",
  "MCT Oil",
  "Sport Bars",
  "Sport Multivitamins",
  "Whey Protein",
  "Bath",
  "Aromatherapy",
  "Bath & Shower",
  "Body & Massage Oils",
  "Hair Care",
  "Lip Care",
  "Lotion",
  "Medicine Cabinet",
  "Men's Grooming",
  "Oral Care",
  "Personal Care",
  "Beauty",
  "Cleanse, Tone & Scrub",
  "Face Masks & Peels",
  "Gift Sets",
  "Moisturizers & Creams",
  "K-Beauty",
  "Lip Care",
  "Makeup",
  "Makeup Brushes & Tools",
  "Treatments & Serums",
  "Grocery",
  "Baking & Flour",
  "Butters & Spreads",
  "Coconut Oil",
  "Coffee",
  "Honey & Sweetners",
  "Nuts & Seeds",
  "Spices",
  "Tea",
  "Healthy Home",
  "Baby",
  "Bath, Skin & Hair",
  "Children's Health",
  "Feeding",
  "Moms & Maternity",
  "Pets",
  "Pet Food",
  "Pet Grooming",
  "Pet Supplements",
  "21st Century",
  "Acure",
  "Andalou Naturals",
  "Aura Cacia",
  "Azelique",
  "Bluebonnet Nutrition",
  "California Gold Nutrition",
  "Carlson Labs",
  "ChildLife",
  "Country Life",
  "Derma E",
  "Desert Essence",
  "Doctor's Best",
  "Enzymedica",
  "Frontier Natural Products",
  "Garden of Life",
  "iHerb Exclusives",
  "Jarrow Formulas",
  "K-Beauty",
  "Lake Avenue Nutrition",
  "Life-flo",
  "Life Extension",
  "Manuka Doctor",
  "MegaFood",
  "Mild By Nature",
  "MRM",
  "Muscletech",
  "Natrol",
  "Natural Factors",
  "Nature's Answer",
  "Nature's Bounty",
  "Nature's Plus",
  "Nature's Way",
  "Neocell",
  "Nordic Naturals",
  "Now Foods",
  "Nubian Heritage",
  "Optimum Nutrition",
  "Oslomega",
  "Paradise Herbs",
  "Pet Naturals of Vermont",
  "Solaray",
  "Solgar",
  "Source Naturals",
  "Sports Research",
  "Thorne Research",
  "Ultamins",
  "Vitables",
  "Weleda",
  "Anti-Aging & Longevity",
  "Ayurveda",
  "Bladder",
  "Bone, Joint & Cartilage",
  "Brain & Cognitive",
  "Circulatory System",
  "Colon",
  "Common Cold & Flu",
  "Detox & Cleanse",
  "Digestive System",
  "Ears",
  "Energy",
  "Eye & Vision",
  "Hair, Skin & Nails",
  "Heart",
  "Immune System",
  "Pain Relief",
  "Respiratory System",
  "Seasonal Allergies",
  "Sleep",
  "Weight Loss",
  "Kids Health",
  "Men's Health",
  "Women's Health",
  "Senior Health",
];

minify();
